DROP TABLE IF EXISTS usuario CASCADE;
DROP TABLE IF EXISTS permissao CASCADE;
DROP TABLE IF EXISTS solicitacao_amizade CASCADE;
DROP TABLE IF EXISTS amizade CASCADE;
DROP TABLE IF EXISTS receita CASCADE;
DROP TABLE IF EXISTS ingrediente CASCADE;
DROP TABLE IF EXISTS receita_ingrediente CASCADE;
DROP TABLE IF EXISTS post CASCADE;
DROP TABLE IF EXISTS comentario CASCADE;
DROP TABLE IF EXISTS curtir CASCADE;
DROP TABLE IF EXISTS amizade_usuario CASCADE;
DROP TABLE IF EXISTS post_usuario CASCADE;
DROP TABLE IF EXISTS post_comentario CASCADE;
DROP TABLE IF EXISTS post_curtir CASCADE;

CREATE TABLE usuario(
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	nome VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL,
	senha VARCHAR(128) NOT NULL,
	apelido VARCHAR(50),
	data_nascimento DATE NOT NULL,
	imagem_perfil_url VARCHAR(512),
	ativo BOOLEAN DEFAULT(TRUE) NOT NULL
);

ALTER TABLE usuario ADD CONSTRAINT pk_usuario PRIMARY KEY(id);
ALTER TABLE usuario ADD CONSTRAINT uk_usuario_email UNIQUE(email);

CREATE TABLE permissao (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	funcao VARCHAR(100) NOT NULL,
	usuario_id BIGINT NOT NULL
);

ALTER TABLE permissao ADD CONSTRAINT pk_permissao PRIMARY KEY (id);
ALTER TABLE permissao ADD CONSTRAINT uk_permissao UNIQUE (funcao, usuario_id);
ALTER TABLE permissao ADD CONSTRAINT fk_permissao_usuario FOREIGN KEY (usuario_id) REFERENCES usuario;


CREATE TABLE amizade(
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	data_inicio DATE NOT NULL,
	id_usuario_um BIGINT NOT NULL,
	id_usuario_dois BIGINT NOT NULL
);

ALTER TABLE amizade ADD CONSTRAINT pk_amizade PRIMARY KEY(id);
ALTER TABLE amizade ADD CONSTRAINT fk_amizade_usuario_um FOREIGN KEY(id_usuario_um) REFERENCES usuario;
ALTER TABLE amizade ADD CONSTRAINT fk_amizade_usuario_dois FOREIGN KEY(id_usuario_dois) REFERENCES usuario;

CREATE TABLE solicitacao_amizade(
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	id_usuario_solicitado BIGINT NOT NULL,
	id_usuario_solicitante BIGINT NOT NULL,
	data_solicitacao DATE NOT NULL,
	situacao VARCHAR(15) NOT NULL
);

ALTER TABLE solicitacao_amizade ADD CONSTRAINT pk_solicitacao_amizade PRIMARY KEY(id);
ALTER TABLE solicitacao_amizade ADD CONSTRAINT fk_solicitacao_amizade_usuario_solicitado FOREIGN KEY(id_usuario_solicitado) REFERENCES usuario;
ALTER TABLE solicitacao_amizade ADD CONSTRAINT fk_solicitacao_amizade_usuario_solicitante FOREIGN KEY(id_usuario_solicitante) REFERENCES usuario;
ALTER TABLE solicitacao_amizade ADD CONSTRAINT ck_solicitacao_amizade CHECK(situacao IN('ACEITA', 'PENDENTE', 'RECUSADA'));

CREATE TABLE receita(
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	titulo VARCHAR (100) NOT NULL,
	descricao VARCHAR(500) NOT NULL,
	tempo_preparo time NOT NULL,
	avaliacao DECIMAL 
);

ALTER TABLE receita ADD CONSTRAINT pk_receita PRIMARY KEY(id);

CREATE TABLE ingrediente(
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	nome VARCHAR(100) NOT NULL
);

ALTER TABLE ingrediente ADD CONSTRAINT pk_ingrediente PRIMARY KEY (id);
ALTER TABLE ingrediente ADD CONSTRAINT uk_ingrediente UNIQUE(nome);

CREATE TABLE post(
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	data_publicacao DATE NOT NULL,
	privacidade VARCHAR(100) NOT NULL,
	id_receita BIGINT NOT NULL,
	ativo BOOLEAN DEFAULT(true) NOT NULL
);

ALTER TABLE post ADD CONSTRAINT pk_post PRIMARY KEY(id);
ALTER TABLE post ADD CONSTRAINT ck_post CHECK(privacidade IN('PUBLICO', 'PRIVADO'));
ALTER TABLE post ADD CONSTRAINT fk_post_receita FOREIGN KEY(id_receita) REFERENCES receita;

CREATE TABLE comentario(
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	texto VARCHAR(500) NOT NULL,
	id_usuario_remetente BIGINT NOT NULL,
	id_usuario_destinatario BIGINT NOT NULL,
	ativo BOOLEAN DEFAULT(true) NOT NULL
);

ALTER TABLE comentario ADD CONSTRAINT pk_comentario PRIMARY KEY(id);
ALTER TABLE comentario ADD CONSTRAINT fk_comentario_usuario_remetente FOREIGN KEY(id_usuario_remetente) REFERENCES usuario;
ALTER TABLE comentario ADD CONSTRAINT fk_comentario_usuario_destinatario FOREIGN KEY(id_usuario_destinatario) REFERENCES usuario;

CREATE TABLE curtir(
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	id_usuario_remetente BIGINT NOT NULL,
	id_usuario_destinatario BIGINT NOT NULL,
	ativo boolean NOT NULL
);

ALTER TABLE curtir ADD CONSTRAINT pk_curtir PRIMARY KEY(id);
ALTER TABLE curtir ADD CONSTRAINT fk_comentario_usuario_remetente FOREIGN KEY(id_usuario_remetente) REFERENCES usuario;
ALTER TABLE curtir ADD CONSTRAINT fk_comentario_usuario_destinatario FOREIGN KEY(id_usuario_destinatario) REFERENCES usuario;

CREATE TABLE receita_ingrediente(
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	id_receita BIGINT NOT NULL,
	id_ingrediente BIGINT NOT NULL
);


ALTER TABLE receita_ingrediente ADD CONSTRAINT pk_receita_ingrediente PRIMARY KEY(id);
ALTER TABLE receita_ingrediente ADD CONSTRAINT fk_receita_ingrediente_receita FOREIGN KEY(id_receita) REFERENCES receita;
ALTER TABLE receita_ingrediente ADD CONSTRAINT fk_receita_ingrediente_ingrediente FOREIGN KEY (id_ingrediente) REFERENCES ingrediente;

CREATE TABLE amizade_usuario(
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	id_amizade BIGINT NOT NULL,
	id_usuario BIGINT NOT NULL
);

ALTER TABLE amizade_usuario ADD CONSTRAINT pk_amizade_usuario PRIMARY KEY(id);
ALTER TABLE amizade_usuario ADD CONSTRAINT fk_amizade_usuario_amizade FOREIGN KEY(id_amizade) REFERENCES amizade;
ALTER TABLE amizade_usuario ADD CONSTRAINT fk_amizade_usuario_usuario FOREIGN KEY (id_usuario) REFERENCES usuario;

CREATE TABLE post_usuario(
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	id_post BIGINT NOT NULL,
	id_usuario BIGINT NOT NULL
);

ALTER TABLE post_usuario ADD CONSTRAINT pk_post_usuario PRIMARY KEY (id);
ALTER TABLE post_usuario ADD CONSTRAINT fk_post_usuario_post FOREIGN KEY(id_post) REFERENCES post;
ALTER TABLE post_usuario ADD CONSTRAINT fk_post_usuario_usuario FOREIGN KEY(id_usuario) REFERENCES usuario;

CREATE TABLE post_comentario(
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	id_post BIGINT NOT NULL,
	id_comentario BIGINT NOT NULL
);

ALTER TABLE post_comentario ADD CONSTRAINT pk_post_comentario PRIMARY KEY(id);
ALTER TABLE post_comentario ADD CONSTRAINT fk_post_comentario_post FOREIGN KEY(id_post) REFERENCES post;
ALTER TABLE post_comentario ADD CONSTRAINT fk_post_comentario_comentario FOREIGN KEY(id_comentario) REFERENCES comentario;

CREATE TABLE post_curtir(
	id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	id_post BIGINT NOT NULL,
	id_curtir BIGINT NOT NULL
);

ALTER TABLE post_curtir ADD CONSTRAINT pk_post_curtir PRIMARY KEY(id);
ALTER TABLE post_curtir ADD CONSTRAINT fk_post_curtir_post FOREIGN KEY(id_post) REFERENCES post;
ALTER TABLE post_curtir ADD CONSTRAINT fk_post_curtir_curtir FOREIGN KEY(id_curtir) REFERENCES curtir;